### ISSUE TITLE
Flare: Investigating & Fixing some errors // Hacktoberfest 2019

### ISSUE THREAD

**Issue by PDesire** [thepublictransport/thepublictransport-app#10]
Some problems with Flare appeared now which are sometimes reproducible and sometimes extremely random. Some which appeared to me and which I could not regularly reproduce:

- `could not get 'iterator' of null` (Flutter didn't give me some helpful logs)
- Stopping background animation on dark theme (infinite loop wanted)

Is that a Flare issue ? Should we switch to Lottie ? Are there any reproducible steps to get these bugs ?

**Comment by sventropy** [comment]
Cloning your repository, the app cannot even be built due to compiler issues related to flare:

```
Compiler message:
../bin/flutter/.pub-cache/hosted/pub.dartlang.org/flare_flutter-1.5.8/l
ib/flare.dart:601:14: Error: The method 'FlutterActor.makeShapeNode' has fewer
positional arguments than those of overridden method 'Actor.makeShapeNode'.
  ActorShape makeShapeNode() {
             ^
../bin/flutter/.pub-cache/hosted/pub.dartlang.org/flare_dart-1.4.9/lib/
actor.dart:68:14: Context: This is the overridden method ('makeShapeNode').
  ActorShape makeShapeNode(ActorShape source) {
             ^
Compiler failed on
~/thepublictransport-app/lib/main.dart
```

**Comment by PDesire** [comment]
The latest one, and this bug never appeared to me which is scary

**Comment by sventropy** [comment]
Since the attempt above was done trying to deploy to the iOS simulator, I freshly installed Android Studio and an Android SDK29 AVD to verify the issue there.

Two files, `key.properties` and `api.keys` are missing from `./android/`. Of course, it makes sense to not store the keys in git, but the files with properties should exist, otherwise gradle will fail.
After adding the files, the same issue as above re-occurs. I also upgraded flutter to Flutter 1.9.1+hotfix.4 (latest stable), but the issue remains.

**Comment by PDesire** [comment]
As the usage for Flare will be stopped in the future, and will be shrinked down right now, this issue is obsolete.
